server:
  port: 9096

spring:
  application:
    name: invoice
  datasource:
    url: jdbc:mysql://localhost:3306/invoice
    username: root
    password: root
  jpa.hibernate.ddl-auto: update
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka





